name: IOS CMake

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode version
        run: /usr/bin/xcodebuild -version
             
      - name: Create assets dir
        run: mkdir project/assets

      - name: Install dependencies
        run: pip3 install --upgrade click
             
      - name: Build with Xcode (CMake)
        run: |
          cd workspaces/build-scripts/
          python3 supernova.py --build --platform ios